### ISSUE TITLE
Update docs theme

### ISSUE THREAD

**Issue by DenverCoder1** [nextcord/nextcord-ext-ipc#15]
The theme can be improved to be more consistent with https://github.com/nextcord/nextcord-ext-menus

**Comment by Skelmis** [comment]
Do you mean attempting to directly mirror the menus theme?

**Comment by DenverCoder1** [comment]
Yeah, I think it would make sense to have ext menus and ext ipc use the same theme. I feel the main lib should be a different theme, though, as to make it clear that it is installed separately.
